#!/bin/bash
GENESISPATH="$(find . -maxdepth 1 -type d -name '*genesis*' -print -quit)"

# Installing pagages
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys BBEBDCB318AD50EC6865090613B00F1FD2C19886
echo deb http://repository.spotify.com stable non-free | sudo tee /etc/apt/sources.list.d/spotify.list
sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install -fy $(grep -vE "^\s*#" $GENESISPATH/apt  | tr "\n" " ")
sudo apt-get autoremove -y

# Installing Python modules
sudo pip install -r $GENESISPATH/python/python_requirements
sudo pip3 install -r $GENESISPATH/python/python3_requirements

# Setup SSH-key
ssh-keygen -t rsa -b 4096 -C "gabriel.c.salla@gmail.com" -f ~/.ssh/id_rsa
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_rsa
printf '\n%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
cat ~/.ssh/id_rsa.pub
printf '%*s\n\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -

# GitHub
while true
do
  echo "Add key to GitHub and press a key to continue"
  read -n 1 -s
  echo "Testing GitHub key"
  ssh -T git@github.com >/dev/null 2>/dev/null
  RESULT=$?
  if [ $RESULT -eq 1 ]; then
    echo "Test successful"
    break
  else
    echo "Test failed"
  fi
done

# FZF
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install

# Oh-my-zsh
sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
chsh -s /usr/bin/zsh
git clone git@github.com:powerline/fonts.git
mkdir ~/.fonts
mv ./fonts/Inconsolata-g/Inconsolata-g\ for\ Powerline.otf ~/.fonts/
rm -rf ./fonts
fc-cache -vf ~/.fonts
git clone git@github.com:zsh-users/zsh-syntax-highlighting.git ~/zsh-syntax-highlighting
sudo mv ~/zsh-syntax-highlighting ~/.oh-my-zsh
git clone git@github.com:zsh-users/zsh-autosuggestions ~/zsh-autosuggestions
sudo mv ~/zsh-autosuggestions ~/.oh-my-zsh

# Postman
wget https://dl.pstmn.io/download/latest/linux64 -O ./postman.tar.gz
sudo tar -xzf postman.tar.gz -C ~
rm postman.tar.gz

# Slack
wget https://downloads.slack-edge.com/linux_releases/slack-desktop-2.6.2-amd64.deb -O slack.deb
sudo dpkg -i slack.deb
rm slack.deb

# Sublime text 3
wget https://download.sublimetext.com/sublime-text_build-3126_amd64.deb -O sublime.deb
sudo dpkg -i sublime.deb
rm sublime.deb

SUBLIMEPATH=$GENESISPATH/sublime
# Sublime text 3 - Packages
wget https://packagecontrol.io/Package%20Control.sublime-package -O ~/.config/sublime-text-3/Installed\ Packages/Package\ Control.sublime-package
cp $SUBLIMEPATH/packages ~/.config/sublime-text-3/Packages/User/Package\ Control.sublime-settings
# Sublime text 3 - Settings
cp $SUBLIMEPATH/settings ~/.config/sublime-text-3/Packages/User/Preferences.sublime-settings
# Sublime text 3 - Keymap
cp $SUBLIMEPATH/keymap ~/.config/sublime-text-3/Packages/User/Default\ \(Linux\).sublime-keymap

# Cloning repositories
mkdir ~/repositories
git clone git@github.com:pagarme/ops.git ~/repositories/ops
git clone git@github.com:pagarme/opsutils.git ~/repositories/opsutils
sudo pip3 install ~/repositories/opsutils

# Copying files
cp $GENESISPATH/scripts ~/scripts -r
cp $GENESISPATH/templates/vimrc ~/.vimrc
sudo cp $GENESISPATH/templates/agnoster_custom.zsh-theme ~/.oh-my-zsh/
cp $GENESISPATH/templates/zshrc ~/.zshrc
cp $GENESISPATH/templates/gitconfig ~/.gitconfig
cp $GENESISPATH/templates/gtk_css ~/.config/gtk-3.0/gtk.css
cp $GENESISPATH/templates/gtk_settings ~/.config/gtk-3.0/settings.ini

# Gnome settings
cat $GENESISPATH/gnome/settings | xargs -L 1 gsettings set

# Gnome extensions
wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/ubuntugnome/gnomeshell-extension-manage -O ~/gnomeshell-extension-manage
sudo chmod +x ~/gnomeshell-extension-manage
~/gnomeshell-extension-manage --install --extension-id 120 # System monitor
~/gnomeshell-extension-manage --install --extension-id 495 # Top Icons
cat ./gnome/extensions | xargs gsettings set org.gnome.shell enabled-extensions
rm ~/gnomeshell-extension-manage

# Default text editor to Sublime
sudo sed -i 's/gedit/sublime_text/' /usr/share/applications/defaults.list
cp /usr/share/applications/defaults.list ~/.local/share/applications/defaults.list