export ZSH=$HOME/.oh-my-zsh
export EDITOR=nvim

ZSH_THEME="kphoen_custom"

plugins=(git)

source $ZSH/oh-my-zsh.sh
prompt_context () { }

# Fast folders
alias watchdog="cd ~/repositories/watchdog"
alias ops="cd ~/repositories/ops"
alias opsutils="cd ~/repositories/opsutils"

alias p3="python3"
alias postman="~/Postman/Postman"

# Scripts
alias opsbox="~/scripts/opsbox"
alias session="python3 ~/scripts/getsession.py"

# Database
db(){
    if [ $# -eq 0 ]
        then
            echo "Missing database reference"
        else
            echo "Connecting to $1"
            pgcli -D $1
    fi
}

# Given a process name, start 'top' with the running process
ntop(){
    if [ $# -eq 0 ]
      then
        echo "No process name supplied"
    else
        pids=$(pgrep -d',' "$1")
        [[ -z "$pids" ]] && echo "No process named $1 in execution" || top -p $pids
    fi
}

# Start a local venv if exists, or use the one in the home
venv(){
    if [ $# -eq 0 ]
        then
            VENV_NAME='ve'
        else
            VENV_NAME=$1
    fi
    if [[ -d ./$VENV_NAME ]]; then
        echo 'Starting local virtual environment'
        source ./$VENV_NAME/bin/activate
    else
        echo 'Starting home virtual environment'
        source $HOME/ve/bin/activate
    fi
}

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source ~/.oh-my-zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.oh-my-zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
venv
