export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="agnoster_custom"

plugins=(git)

source $ZSH/oh-my-zsh.sh

prompt_context () { }

alias p3="python3"
alias gopen="xdg-open"

alias postman="~/Postman/Postman"
alias pgadmin="source ~/pgadmin4/bin/activate && python ~/pgadmin4/lib/python2.7/site-packages/pgadmin4/pgAdmin4.py" 
alias vpn="sudo openvpn --config ~/.ovpn/config.ovpn --ca ~/.ovpn/ca.crt --cert ~/.ovpn/client.crt --key ~/.ovpn/client.key"

# Database
alias dbreplica="pgcli -h replica-db.pagarme.net -p 5432 -U ops -W -d pagarme"
alias dbfinops="pgcli -h finops-intdb.pagarme.net -p 5432 -U ops -W -d pagarme"
alias dbredshift="pgcli -h dataops-db.pagarme.net -p 5439 -U pagarme_ops -W -d pagarme"

# Scripts
alias opsbox="~/scripts/opsbox"
alias fetch="python3 ~/scripts/fetch.py"

# Given a process name, start 'top' with the running process
ntop(){
    if [ $# -eq 0 ]
      then
        echo "No process name supplied"
    else
        pids=$(pgrep -d',' "$1")
        [[ -z "$pids" ]] && echo "No process named $1 in execution" || top -p $pids
    fi
}

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source ~/.oh-my-zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.oh-my-zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
